#!/bin/bash
# =============================================================================
# SaltStack Minion 安装脚本 (Ubuntu/Debian)
# 从 AppHub 下载并安装 SaltStack Minion
# =============================================================================

set -e

# 参数检查
if [ $# -lt 3 ]; then
    echo "Usage: $0 <APPHUB_URL> <SALT_VERSION> <MASTER_HOST> [MINION_ID]"
    echo "Example: $0 http://192.168.0.200:53434 3007.8 192.168.18.154 my-minion-01"
    exit 1
fi

APPHUB_URL="$1"
SALT_VERSION="$2"
MASTER_HOST="$3"
MINION_ID="${4:-$(hostname)}"

echo "=========================================="
echo "Installing SaltStack Minion from AppHub"
echo "AppHub URL: ${APPHUB_URL}"
echo "SaltStack Version: ${SALT_VERSION}"
echo "Master Host: ${MASTER_HOST}"
echo "Minion ID: ${MINION_ID}"
echo "=========================================="

# 检测架构
ARCH=$(dpkg --print-architecture 2>/dev/null || echo "amd64")
echo "Detected architecture: ${ARCH}"

# 设置AppHub包路径
APPHUB_BASE="${APPHUB_URL}/pkgs/saltstack-deb"

# 下载所需的SaltStack包
cd /tmp
echo "Downloading SaltStack packages from AppHub..."

# 下载依赖包
echo "Downloading salt-common_${SALT_VERSION}_${ARCH}.deb..."
curl -fsSL "${APPHUB_BASE}/salt-common_${SALT_VERSION}_${ARCH}.deb" -o salt-common.deb || {
    echo "Failed to download salt-common from AppHub"
    exit 1
}

# 下载salt-minion
echo "Downloading salt-minion_${SALT_VERSION}_${ARCH}.deb..."
curl -fsSL "${APPHUB_BASE}/salt-minion_${SALT_VERSION}_${ARCH}.deb" -o salt-minion.deb || {
    echo "Failed to download salt-minion from AppHub"
    exit 1
}

echo "Installing SaltStack packages..."
# 更新包索引
sudo apt-get update -y || true

# 安装Python依赖
echo "Installing Python dependencies..."
sudo apt-get install -y python3 python3-pip python3-setuptools || true

# 安装salt-common（依赖包）
echo "Installing salt-common..."
sudo dpkg -i salt-common.deb || sudo apt-get install -f -y

# 安装salt-minion
echo "Installing salt-minion..."
sudo dpkg -i salt-minion.deb || sudo apt-get install -f -y

# 清理临时文件
rm -f salt-common.deb salt-minion.deb

# 验证安装
echo "Verifying installation..."
salt-minion --version || {
    echo "Salt Minion installation verification failed"
    exit 1
}

# 配置 Salt Minion
echo "Configuring Salt Minion..."
sudo mkdir -p /etc/salt

# 创建 minion 配置文件
sudo tee /etc/salt/minion > /dev/null <<EOF
# SaltStack Minion Configuration
# Auto-generated by install-salt-minion-deb.sh

master: ${MASTER_HOST}
id: ${MINION_ID}

# 自动接受 master 的 key
master_finger: ''

# 日志配置
log_level: info
log_file: /var/log/salt/minion

# 其他配置
retry_dns: 30
retry_dns_count: 3
acceptance_wait_time: 10
acceptance_wait_time_max: 60
EOF

echo "Configuration written to /etc/salt/minion"

# 启动并启用 Salt Minion 服务
echo "Starting Salt Minion service..."
sudo systemctl daemon-reload || true
sudo systemctl enable salt-minion || true
sudo systemctl restart salt-minion || true

# 等待服务启动
sleep 2

# 检查服务状态
if sudo systemctl is-active --quiet salt-minion; then
    echo "Salt Minion service is running"
else
    echo "Warning: Salt Minion service may not be running properly"
    sudo systemctl status salt-minion --no-pager || true
fi

echo "=========================================="
echo "SaltStack Minion installed successfully from AppHub"
echo "Version: $(salt-minion --version)"
echo "Master: ${MASTER_HOST}"
echo "Minion ID: ${MINION_ID}"
echo "Service Status: $(systemctl is-active salt-minion 2>/dev/null || echo 'unknown')"
echo ""
echo "Next steps:"
echo "1. On Salt Master, accept the minion key:"
echo "   salt-key -a ${MINION_ID}"
echo "2. Test connectivity:"
echo "   salt '${MINION_ID}' test.ping"
echo "=========================================="
