# JupyterHub Configuration Template
# Environment: {{ENVIRONMENT}}
# Authentication: {{AUTH_TYPE}}
# Generated by build.sh at {{GENERATION_TIME}}

import os
import sys

# Basic configuration
c = get_config()

# Hub configuration
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = {{JUPYTERHUB_HUB_PORT}}
c.JupyterHub.port = {{JUPYTERHUB_PORT}}

# Base URL configuration
c.JupyterHub.base_url = '{{JUPYTERHUB_BASE_URL}}'
c.JupyterHub.bind_url = 'http://0.0.0.0:{{JUPYTERHUB_PORT}}{{JUPYTERHUB_BASE_URL}}'

# Hub connection URL for spawned containers
c.JupyterHub.hub_connect_url = 'http://{{JUPYTERHUB_HUB_CONNECT_HOST}}:{{JUPYTERHUB_HUB_PORT}}{{JUPYTERHUB_BASE_URL}}'

# Public URL configuration
c.JupyterHub.public_url = '{{JUPYTERHUB_PUBLIC_URL}}'

# Security
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.proxy_auth_token = os.environ.get('CONFIGPROXY_AUTH_TOKEN', '{{CONFIGPROXY_AUTH_TOKEN}}')

# Database configuration
c.JupyterHub.db_url = os.environ.get('JUPYTERHUB_DB_URL', '{{JUPYTERHUB_DB_URL}}')

# Logging
c.JupyterHub.log_level = '{{JUPYTERHUB_LOG_LEVEL}}'
c.Application.log_level = '{{JUPYTERHUB_LOG_LEVEL}}'

# Session timeout configuration
c.JupyterHub.cookie_max_age_days = {{SESSION_TIMEOUT_DAYS}}

# Authentication Configuration
{{AUTH_CONFIG}}

# Spawner Configuration
{{SPAWNER_CONFIG}}

# Admin users
c.Authenticator.admin_users = {{{ADMIN_USERS}}}

# Iframe support for embedding JupyterHub
c.JupyterHub.tornado_settings = {
    'headers': {
        'X-Frame-Options': 'SAMEORIGIN',
        'Content-Security-Policy': "frame-ancestors 'self' http://localhost:8080 http://0.0.0.0:8080 http://172.20.10.11:8080;"
    }
}

# Additional environment-specific configuration
{{ADDITIONAL_CONFIG}}
