# JupyterHub Configuration Template
# Environment: development
# Authentication: local
# Generated by build.sh at 2025-08-30 14:14:42

import os
import sys

# Basic configuration
c = get_config()

# Hub configuration
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8081
c.JupyterHub.port = 8000

# Base URL configuration
c.JupyterHub.base_url = '/jupyter/'
c.JupyterHub.bind_url = 'http://0.0.0.0:8000/jupyter/'

# Hub connection URL for spawned containers
c.JupyterHub.hub_connect_url = 'http://jupyterhub:8081/jupyter/'

# Public URL configuration
c.JupyterHub.public_url = 'http://localhost:8080/jupyter/'

# Security
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.proxy_auth_token = os.environ.get('CONFIGPROXY_AUTH_TOKEN', 'ai-infra-proxy-token-dev')

# Database configuration
c.JupyterHub.db_url = os.environ.get('JUPYTERHUB_DB_URL', 'sqlite:///jupyterhub.sqlite')

# Logging
c.JupyterHub.log_level = 'INFO'
c.Application.log_level = 'INFO'

# Session timeout configuration
c.JupyterHub.cookie_max_age_days = 7

# Authentication Configuration
# Backend Integrated Authentication Configuration
from backend_integrated_auth import BackendIntegratedAuthenticator

c.JupyterHub.authenticator_class = BackendIntegratedAuthenticator
c.BackendIntegratedAuthenticator.backend_url = 'http://backend:8082'
c.BackendIntegratedAuthenticator.jwt_secret = os.environ.get('JWT_SECRET', '')

# User management configuration
c.Authenticator.allow_all = True  # User permissions controlled by backend
c.Authenticator.admin_users = set()  # Admins determined by backend API

# Auto-login configuration
c.Authenticator.auto_login = False
c.Authenticator.auth_refresh_age = 3600
c.Authenticator.refresh_pre_spawn = True

# Spawner Configuration
# Docker Spawner Configuration for Development
from dockerspawner import DockerSpawner

c.JupyterHub.spawner_class = DockerSpawner
c.DockerSpawner.image = os.environ.get('SINGLEUSER_IMAGE', 'ai-infra-singleuser:latest')
c.DockerSpawner.network_name = 'ai-infra-matrix_default'
c.DockerSpawner.remove = True

# Resource limits
c.DockerSpawner.mem_limit = '2G'
c.DockerSpawner.cpu_limit = 1.0

# Volume mounts
c.DockerSpawner.volumes = {
    'jupyterhub-user-{username}': '/home/jovyan/work',
    '/srv/shared-notebooks': '/home/jovyan/shared'
}

# Environment variables for single-user containers
c.DockerSpawner.environment = {
    'JUPYTER_ENABLE_LAB': '1',
    'AI_INFRA_API_URL': 'http://backend:8082',
    'JUPYTERHUB_K8S_NAMESPACE': 'ai-infra-users',
}

# Use internal IP for communication
c.DockerSpawner.use_internal_ip = True

# Admin users
c.Authenticator.admin_users = {{{ADMIN_USERS}}}

# Additional environment-specific configuration

