# JupyterHub Configuration Template
# Environment: development
# Authentication: local
# Generated by build.sh at Sat Aug 30 00:57:22 CST 2025

import os
import sys

# Basic configuration
c = get_config()

# Hub configuration
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8081
c.JupyterHub.port = 8000

# Security
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.proxy_auth_token = os.environ.get('CONFIGPROXY_AUTH_TOKEN', '')

# Database
c.JupyterHub.db_url = os.environ.get('JUPYTERHUB_DB_URL', 'sqlite:///jupyterhub.sqlite')

# Logging
c.JupyterHub.log_level = 'INFO'
c.Application.log_level = 'INFO'

# Docker Spawner Configuration
from dockerspawner import DockerSpawner

c.JupyterHub.spawner_class = DockerSpawner
c.DockerSpawner.image = os.environ.get('SINGLEUSER_IMAGE', 'ai-infra-singleuser:latest')
c.DockerSpawner.network_name = 'ai-infra-matrix_default'
c.DockerSpawner.remove = True

# Resource limits
c.DockerSpawner.mem_limit = '2G'
c.DockerSpawner.cpu_limit = 1.0

# Volume mounts
c.DockerSpawner.volumes = {
    'jupyterhub-user-{username}': '/home/jovyan/work'
}

# Local Authentication Configuration
c.Authenticator.admin_users = {'admin'}
c.Authenticator.allow_all = True
c.LocalAuthenticator.create_system_users = True


