# JupyterHub Configuration Template
# Environment: development
# Authentication: local
# Generated by build.sh at 2025-08-30 14:12:53

import os
import sys

# Basic configuration
c = get_config()

# Hub configuration
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.hub_port = 8081
c.JupyterHub.port = 8000

# Base URL configuration
c.JupyterHub.base_url = '/jupyter/'
c.JupyterHub.bind_url = 'http://0.0.0.0:8000/jupyter/'

# Hub connection URL for spawned containers
c.JupyterHub.hub_connect_url = 'http://jupyterhub:8081/jupyter/'

# Public URL configuration
c.JupyterHub.public_url = 'http://localhost:8080/jupyter/'

# Security
c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/cookie_secret'
c.JupyterHub.proxy_auth_token = os.environ.get('CONFIGPROXY_AUTH_TOKEN', 'ai-infra-proxy-token-dev')

# Database configuration
c.JupyterHub.db_url = os.environ.get('JUPYTERHUB_DB_URL', 'sqlite:///jupyterhub.sqlite')

# Logging
c.JupyterHub.log_level = 'INFO'
c.Application.log_level = 'INFO'

# Session timeout configuration
c.JupyterHub.cookie_max_age_days = 7

# Authentication Configuration


# Spawner Configuration


# Admin users
c.Authenticator.admin_users = {{{ADMIN_USERS}}}

# Additional environment-specific configuration

